name: makevsix

on:
  push:
    tags:
      - '*'

jobs:
  cicd:
    name: cicd
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: clean install dependencies
        run: yarn install

      - name: compile and create vsix
        run: yarn run package

      - name: get-npm-version
        id: package_version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.package_version.outputs.current-version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./vscode-glsllint-${{ steps.package_version.outputs.current-version }}.vsix
          asset_name: vscode-glsllint-${{ steps.package_version.outputs.current-version }}.vsix
          asset_content_type: application/zip
